version: '3.8'

services:
  prestashop:
    image: prestashop/prestashop:1.7.8
    ports:
      - "8080:80"
    environment:
      PS_DEV_MODE: '1'
      PS_INSTALL_MODE: '1'
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWORD: prestashop
    volumes:
      - prestashop_data:/var/www/html

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    volumes:
      - db_data:/var/lib/mysql

volumes:
  prestashop_data:
  db_data: