version: '3.8'

services:
  prestashop:
    image: prestashop-custom:1.2.1
    ports:
      - "19339:443"
    environment:
      PS_DEV_MODE: '1'
      PS_INSTALL_MODE: '0'  # Pominięcie instalacji
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_193151
      DB_USER: root
      DB_PASSWORD: student
    volumes:
      - ./ssl:/etc/apache2/ssl
    depends_on:
      - admin-mysql_db
    networks:
      - prestashop_network
    

  admin-mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: BE_193151
    volumes:
      - db_data:/var/lib/mysql
      - ./db_backup.sql:/docker-entrypoint-initdb.d/db_backup.sql  # Mapowanie pliku z backupem bazy
    networks:
      - prestashop_network
     ports:
      - "3306:3306"



volumes:
  db_data:

networks:
  prestashop_network:
    driver: bridge
