version: '3.8'

services:
  prestashop:
    image: prestashop/prestashop:1.7.8
    ports:
      - "8080:80"
    environment:
      PS_DEV_MODE: '1'
      PS_INSTALL_MODE: '0'  # Pominięcie instalacji
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWORD: prestashop
    volumes:
      - ./prestashop_files:/var/www/html  # Lokalne pliki PrestaShop
      - ./logs:/var/www/html/var/logs  # Mapowanie katalogu logs
      - ./checkout.env:/var/www/html/modules/ps_checkout/.env
      - ./mbo.env:/var/www/html/modules/ps_mbo/.env
      - ./metrics.env:/var/www/html/modules/ps_metrics/.env
    depends_on:
      - db
    command: >
      bash -c "mkdir -p /var/www/html/var/cache/dev /var/www/html/var/cache/prod &&
              mkdir -p /var/www/html/var/logs &&
             chmod -R 777 /var/www/html/var/cache &&
             chmod -R 777 /var/www/html/var/logs &&
             apache2-foreground"
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    volumes:
      - db_data:/var/lib/mysql
      - ./db_backup.sql:/docker-entrypoint-initdb.d/db_backup.sql  # Mapowanie pliku z backupem bazy

volumes:
  db_data:
